### ISSUE TITLE
check custom RequiredAPIVersion values

### ISSUE THREAD

**Issue by jasondellaluce** [falcosecurity/plugin-sdk-go#51]
**Motivation**

In the `Info() *plugins.Info` method, the Go SDK sets automatically the `RequiredAPIVersion` field to the latest supported plugin API version. Developers can choose to set their own value too, if desired. However, the SDK does not check that the developer-provided version is semver-compatible with the internal default one. This can cause silent or ambiguous failures due to the fact that the SDK is inherently developed to comply to a certain version of the plugin API.

**Feature**

If developer supply a custom `RequiredAPIVersion` info value, then the SDK should perform a semver check with its internally-supported API version, and output an expressive error if the two versions are incompatible in order to prevent unpredicable failures.

**Alternatives**

**Additional context**

**Comment by Rohith-Raju** [comment]
Hey guys, regarding the check,
> If developer supply a custom RequiredAPIVersion info value, then the SDK should perform a semver check with its internally-supported API version
I found this 
```
#define PLUGIN_API_VERSION_MAJOR 2
#define PLUGIN_API_VERSION_MINOR 0
#define PLUGIN_API_VERSION_PATCH 0

//
// Just some not so smart defines to retrieve plugin api version as string
//
#define QUOTE(str)                  #str
#define EXPAND_AND_QUOTE(str)       QUOTE(str)
#define PLUGIN_API_VERSION          PLUGIN_API_VERSION_MAJOR.PLUGIN_API_VERSION_MINOR.PLUGIN_API_VERSION_PATCH
#define PLUGIN_API_VERSION_STR      EXPAND_AND_QUOTE(PLUGIN_API_VERSION)
``` 
Here we have macros `PLUGIN_API_VERSION_MAJOR` `PLUGIN_API_VERSION_MINOR` `PLUGIN_API_VERSION_PATCH`

#### What would determine a successful check? Should the `custom` API version be greater than `2.0.0`
FOR EXAMPLE:
```
2.1.0
```

**Comment by jasondellaluce** [comment]
A quick test that can help reducing the `k8saudit` plugin CPU usage is configuring it with `useAsync: false` (see: https://github.com/falcosecurity/plugins/tree/master/plugins/k8saudit#configuration). The Falco config would look like:
```yaml
plugins:
  - name: k8saudit
    library_path: libk8saudit.so
    init_config:
      useAsync: false
      ...
    open_params: ...
...
load_plugins: [k8saudit, ...]
```

This will disable an optimization used by the plugin to improve performance by using some extra CPU time.

**Comment by jasondellaluce** [comment]
The version number is compliant with a simplified SemVer check. For reference, here's how we implement the check in the Falco libraries: https://github.com/falcosecurity/libs/blob/master/userspace/libsinsp/version.h#L49

In this case, `RequiredAPIVersion` would be the `requested` version, whereas `PLUGIN_API_VERSION_STR` the version string supported in the SDK.
