### ISSUE TITLE
Build examples in our CI with the minimum required Go version

### ISSUE THREAD

**Issue by jasondellaluce** [falcosecurity/plugin-sdk-go#77]
**Feature**

We would like to:
- Setup a job in our CI that builds our example plugins using the minimum Go version required by the SDK, so that we can catch unexpected Go version requirement changes coming from newly-added dependencies
- Run the example plugins with a given Falco version (maybe the last released one + dev?) so that we can catch trivial bugs in the SDK

**Comment by GLVSKiriti** [comment]
@jasondellaluce I am interested in this issue. Can I take up this issue? I will start working on this !
